# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
# *  CLASS input parameter file  *
# *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

# -------------------------
# ----> General parameters:
# -------------------------

gauge = synchronous
modes = s
l_max_scalars = 2500
output = tCl, mPk

# ----------------------------
# ----> Cosmological parameters:
# ----------------------------

h = 0.67810                       # Dimensionless reduced Hubble parameter (H_0 / (100km/s/Mpc))
#H0 = 67.810                      # Hubble parameter in km/s/Mpc

T_cmb = 2.7255                    # CMB temperature

omega_b = 0.02238280              # Reduced baryon density (Omega*h^2)
#Omega_b =                        # Baryon density
omega_cdm = 0.1201075             # Reduced cold dark matter density (Omega*h^2)
#Omega_cdm =                      # CDM density
Omega_k = 0.                      # Curvature density
Omega_fld = 0                     # Dark Energy as Fluid density
Omega_scf = -1                     # Dark Energy as Scalar field density
Omega_Lambda = 0.0


# If you have respectively 0,1,2, or 3 MASSIVE neutrinos and the default T_ncdm of 0.71611,
# designed to give M_tot/omega_nu of 93.14 eV, and if you want N_eff equal to 3.044,
# then you should pass for N_ur 3.044,2.0308,1.0176, or 0.00441
#N_ur = 3.044                      # Effective number of MASSLESS neutrino species
#N_ncdm = 0                         # Massive neutrino species
N_ur = 2.0308
N_ncdm = 1
m_ncdm = 0.06
# ----------------------------
# ----> Modified gravity parameters:
# ----------------------------

scf_alpha = 0.48  # Non-minimal coupling.
scf_kappa2 = 1.  # Bare gravitational constant.

# ----------------------------
# ----> Scalar field parameters (potential coefficients + initial conditions):
# ----------------------------

scf_tuning_index = 0  # Shooting method for V_0 to close the Friedmann equation.
attractor_ic_scf = no 

scf_parameters = 1e-8, 5.583e-8, 0.0, 0.0173, 0.0

dV0_guess = 1e-6

# Relax the strict radiation domination check to allow for modified gravity in the early Universe.
tol_initial_Omega_r = 5e-1

# ----------------------------------
# ----> Output parameters:
# ----------------------------------

#root = output/default            # Root name of output files
overwrite_root = yes               # Overwrite the output files?
write_background = yes             # Write background parameter table
write_thermodynamics = no         # Write thermodynamics parameter table
#k_output_values = 1e-3,1e-2      # Write perturbations parameter table (at given k)
write_primordial = no             # Write primordial parameter table
write_parameters = yes           # Write used/unused parameter files
write_warnings = yes              # Warn about forgotten/wrong inputs

#Verbosity
input_verbose = 1
background_verbose = 2
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
harmonic_verbose = 1
fourier_verbose = 1
lensing_verbose = 1
output_verbose = 1


root = output/MG_simulation_new

a_ini_over_a_today_default = 1e-11